export const GET_TRELLO_HISTORY_START = 'GET_TRELLO_HISTORY_START';
export const GET_TRELLO_HISTORY_SUCCESS = 'GET_TRELLO_HISTORY_SUCCESS';
export const GET_TRELLO_HISTORY_FAILED = 'GET_TRELLO_HISTORY_FAILED';

export const SWITCH_VIEW_MODE = 'SWITCH_VIEW_MODE';

