export const GET_CURRENT_URL_REQUEST = 'GET_CURRENT_URL_REQUEST';
export const GET_CURRENT_URL_SUCCESS = 'GET_CURRENT_URL_SUCCESS';

export const GET_TRELLO_HISTORY_START = 'GET_TRELLO_HISTORY_START';
export const GET_TRELLO_HISTORY_SUCCESS = 'GET_TRELLO_HISTORY_SUCCESS';
export const GET_TRELLO_HISTORY_FAILED = 'GET_TRELLO_HISTORY_FAILED';

